---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: reloader-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./reloader
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-source
  targetNamespace: reloader

