kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.21.2
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # extraMounts:
  # - hostPath: /Users/warapong/Desktop/src/volume/redis
  #   containerPath: /data
# - role: worker
# - role: worker
# - role: worker
networking:
  disableDefaultCNI: true
#   kubeProxyMode: none