apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: sample
spec:
  replicas: 10
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: sample
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 10
        - pause: {}
        - setWeight: 10
        - pause: {}
