---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubernetes
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./reloader
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes
  targetNamespace: reloader

