---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kubernetes
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: dev
  url: https://github.com/warapong-pj/kubernetes.git

