---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: 3.8.2
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: metrics-server
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
  values:
    args:
      - --kubelet-insecure-tls

