---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deployments/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: reloader
  targetNamespace: reloader

