---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    tag: v0.0.110
  url: https://github.com/stakater/Reloader.git

