apiVersion: v1
kind: Service
metadata:
  name: sample-active
  labels:
    app: sample
spec:
  ports:
  - port: 80
  selector:
    app: sample
---
apiVersion: v1
kind: Service
metadata:
  name: sample-preview
  labels:
    app: sample
spec:
  ports:
  - port: 80
  selector:
    app: sample